#if os(macOS)
import Foundation
import Testing
@testable import Personal_Finance

@MainActor
struct FormiCLIInstallerTests {
    @Test(arguments: [
        ["import", "FILE", "--yes", "--allow-duplicates"],
        ["preview", "--json", "FILE"],
        ["import", "--book", "00000000-0000-0000-0000-000000000001", "FILE", "--yes"],
        ["preview", "FILE"]
    ])
    func installedLauncherRoutesSelectedFilesToStdinAndPreservesFlags(_ arguments: [String]) throws {
        try withFixture { executable, launcher, file in
            let payload = "[{\"description\":\"Prova sintetica €\"}]\n"
            try Data(payload.utf8).write(to: file)
            try FormiCLIInstaller.writeLauncher(to: launcher, executable: executable)
            let actual = arguments.map { $0 == "FILE" ? file.path : $0 }
            let expected = ["--expect-channel", FormiCLIInstaller.channel] + arguments.map { $0 == "FILE" ? "-" : $0 }
            let (status, output) = try run(launcher, arguments: actual)
            #expect(status == 0)
            #expect(output == expected.joined(separator: " ") + "\n")
        }
    }

    @Test(arguments: [["import", "-", "--yes"], ["preview", "--json", "-"], ["accounts"]])
    func installedLauncherPreservesStdinAndOtherCommands(_ arguments: [String]) throws {
        try withFixture { executable, launcher, _ in
            try FormiCLIInstaller.writeLauncher(to: launcher, executable: executable)
            let payload = "[]\n"
            let (status, output) = try run(launcher, arguments: arguments, input: payload)
            let expected = ["--expect-channel", FormiCLIInstaller.channel] + arguments
            #expect(status == 0)
            #expect(output == expected.joined(separator: " ") + "\n")
        }
    }

    @Test func missingSourceDoesNotInvokeTheCLI() throws {
        try withFixture { executable, launcher, file in
            try FormiCLIInstaller.writeLauncher(to: launcher, executable: executable)
            let (status, output) = try run(launcher, arguments: ["import", file.path, "--yes"])
            #expect(status != 0)
            #expect(output.isEmpty)
        }
    }

    private func withFixture(_ body: (URL, URL, URL) throws -> Void) throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent("CLI '\(UUID()) € $(printf injected)")
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }
        let directory = root.appendingPathComponent("Formi.app/Contents/MacOS")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let executable = directory.appendingPathComponent("formi")
        // Use a signed system executable: the sandbox forbids executing scripts
        // generated by the test host. echo exposes the arguments received by exec.
        try FileManager.default.createSymbolicLink(at: executable, withDestinationURL: URL(fileURLWithPath: "/bin/echo"))
        try body(executable, root.appendingPathComponent("launcher"), root.appendingPathComponent("movimenti ' € $(printf injected).json"))
    }

    private func run(_ launcher: URL, arguments: [String], input: String = "") throws -> (Int32, String) {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/sh")
        process.arguments = [launcher.path] + arguments
        let source = Pipe(), output = Pipe(), errors = Pipe()
        process.standardInput = source
        process.standardOutput = output
        process.standardError = errors
        try process.run()
        try source.fileHandleForWriting.write(contentsOf: Data(input.utf8))
        try source.fileHandleForWriting.close()
        let data = output.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        if process.terminationStatus != 0 {
            print("Launcher stderr:", String(decoding: errors.fileHandleForReading.readDataToEndOfFile(), as: UTF8.self))
        }
        return (process.terminationStatus, String(decoding: data, as: UTF8.self))
    }
}
#endif
